---
substitutions:
  id_prefix: ratgdov25
  friendly_name: "RATGDOv2.5"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.5"

esp32:
  board: wemos_d1_mini32

# dashboard_import:
#   package_import_url: github://go4ble/esphome-ratgdo/v25board_esp32_d1_mini.yaml@main

packages:
  remote_package:
    url: https://github.com/go4ble/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server
  encryption:
    key: !secret api_server_encryption_key

# improv_serial:

wifi:
  domain: ""
  ap:

mdns:
  disabled: true

captive_portal:

ota:
  - platform: esphome
    password: !secret web_server_password

# logger:
